apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: dist
    port: {{ .Values.rabbitmq.nodePort | add 20000 }}
    targetPort: dist
  - name: stats
    port: 15672
    targetPort: stats
  selector:
    app: {{ template "rabbitmq.name" . }}
    release: "{{ .Release.Name }}"
